server:
  port: 8080

spring:
  jpa.hibernate.ddl-auto: none
  h2.console.enabled: true
  h2.console.path: /h2

  datasource:
    url: jdbc:h2:mem:perfectdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    username: pa_usr
    password: pa_pwd
    driver-class-name: org.h2.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari.connection-timeout: 60000

liquibase.change-log: classpath:db/liquibase-changelog.xml

logging:
  level:
    org.springframework.web: ERROR
    com.tuturself: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file: ../logs/perfect-webapp.log